import subprocess
from pathlib import Path


def push_branch(sandbox_path: str, branch_name: str) -> None:
    """Push the sandbox branch to origin."""
    subprocess.run(
        ["git", "push", "origin", branch_name],
        cwd=sandbox_path,
        check=True,
        capture_output=True,
    )


def create_pull_request(
    sandbox_path: str,
    branch_name: str,
    base_branch: str,
    title: str,
    body: str,
) -> str:
    """Create a PR using gh CLI. Returns the PR URL."""
    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", base_branch,
            "--head", branch_name,
        ],
        cwd=sandbox_path,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def build_pr_body(
    feature_name: str,
    spec: str,
    architecture: str,
    gate_result: dict,
) -> str:
    """Build the PR description body."""
    score = gate_result.get("total_score", "N/A")
    decision = gate_result.get("decision", "N/A")

    return f"""## {feature_name}

**Gate Score:** {score}/15
**Decision:** {decision}

---

### Specification
{spec}

### Architecture
{architecture}

---
*Generated by SoloCarta AI Pipeline*
"""
